# dependabot analyzing maven dependencies
version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
